# Generated by Django 5.0.7 on 2024-08-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shorteneurls",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
