# Generated by Django 5.0.7 on 2024-08-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0002_rename_update_at_shorteneurls_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="url_count",
            field=models.IntegerField(default=0),
        ),
    ]
