# Generated by Django 5.0.7 on 2024-08-09 08:14

import shortener.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_users_url_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorteneurls',
            name='prefix',
            field=models.CharField(default=shortener.models.ShorteneUrls.rand_letter, max_length=50),
        ),
        migrations.AddIndex(
            model_name='shorteneurls',
            index=models.Index(fields=['prefix', 'shortened_url'], name='shortener_s_prefix_e69239_idx'),
        ),
    ]
