# Generated by Django 5.0.7 on 2024-08-21 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0005_shorteneurls_click_statistic"),
    ]

    operations = [
        migrations.AddField(
            model_name="statistic",
            name="custom_params",
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name="TrackingParams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("params", models.CharField(max_length=20)),
                (
                    "shortened_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shortener.shorteneurls",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
